name: secrets-scan

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: ['**']  # catch accidental pushes anywhere
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: secrets-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history reduces false negatives)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --redact --exit-code 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
